sonar.projectKey=Soft3112-TravelPlanner_travel-planner
sonar.organization=soft3112-travelplanner

sonar.sources=backend/src,frontend/project/src
sonar.tests=frontend/project/src
sonar.test.inclusions=frontend/project/src/**/*.test.js,frontend/project/src/**/*.test.ts,frontend/project/src/**/*.test.tsx
sonar.javascript.lcov.reportPaths=frontend/project/coverage/lcov.info
sonar.typescript.lcov.reportPaths=frontend/project/coverage/lcov.info
sonar.exclusions=frontend/project/src/**/*.test.*
sonar.coverage.exclusions=backend/**/*

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=travel-planner
#sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
