/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppTripsIndexRouteImport } from './routes/_app/trips/index'
import { Route as AppSearchIndexRouteImport } from './routes/_app/search/index'
import { Route as AppProfileIndexRouteImport } from './routes/_app/profile/index'
import { Route as AppFavoritesIndexRouteImport } from './routes/_app/favorites/index'
import { Route as AppBudgetIndexRouteImport } from './routes/_app/budget/index'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppAuthRegisterIndexRouteImport } from './routes/_app/auth/register/index'
import { Route as AppAuthLogoutIndexRouteImport } from './routes/_app/auth/logout/index'
import { Route as AppAuthLoginIndexRouteImport } from './routes/_app/auth/login/index'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTripsIndexRoute = AppTripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchIndexRoute = AppSearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritesIndexRoute = AppFavoritesIndexRouteImport.update({
  id: '/favorites/',
  path: '/favorites/',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetIndexRoute = AppBudgetIndexRouteImport.update({
  id: '/budget/',
  path: '/budget/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthRegisterIndexRoute = AppAuthRegisterIndexRouteImport.update({
  id: '/auth/register/',
  path: '/auth/register/',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthLogoutIndexRoute = AppAuthLogoutIndexRouteImport.update({
  id: '/auth/logout/',
  path: '/auth/logout/',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthLoginIndexRoute = AppAuthLoginIndexRouteImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin/': typeof AppAdminIndexRoute
  '/budget/': typeof AppBudgetIndexRoute
  '/favorites/': typeof AppFavoritesIndexRoute
  '/profile/': typeof AppProfileIndexRoute
  '/search/': typeof AppSearchIndexRoute
  '/trips/': typeof AppTripsIndexRoute
  '/auth/login/': typeof AppAuthLoginIndexRoute
  '/auth/logout/': typeof AppAuthLogoutIndexRoute
  '/auth/register/': typeof AppAuthRegisterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/admin': typeof AppAdminIndexRoute
  '/budget': typeof AppBudgetIndexRoute
  '/favorites': typeof AppFavoritesIndexRoute
  '/profile': typeof AppProfileIndexRoute
  '/search': typeof AppSearchIndexRoute
  '/trips': typeof AppTripsIndexRoute
  '/auth/login': typeof AppAuthLoginIndexRoute
  '/auth/logout': typeof AppAuthLogoutIndexRoute
  '/auth/register': typeof AppAuthRegisterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/budget/': typeof AppBudgetIndexRoute
  '/_app/favorites/': typeof AppFavoritesIndexRoute
  '/_app/profile/': typeof AppProfileIndexRoute
  '/_app/search/': typeof AppSearchIndexRoute
  '/_app/trips/': typeof AppTripsIndexRoute
  '/_app/auth/login/': typeof AppAuthLoginIndexRoute
  '/_app/auth/logout/': typeof AppAuthLogoutIndexRoute
  '/_app/auth/register/': typeof AppAuthRegisterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/'
    | '/budget/'
    | '/favorites/'
    | '/profile/'
    | '/search/'
    | '/trips/'
    | '/auth/login/'
    | '/auth/logout/'
    | '/auth/register/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/budget'
    | '/favorites'
    | '/profile'
    | '/search'
    | '/trips'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/register'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/_app/admin/'
    | '/_app/budget/'
    | '/_app/favorites/'
    | '/_app/profile/'
    | '/_app/search/'
    | '/_app/trips/'
    | '/_app/auth/login/'
    | '/_app/auth/logout/'
    | '/_app/auth/register/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trips/': {
      id: '/_app/trips/'
      path: '/trips'
      fullPath: '/trips/'
      preLoaderRoute: typeof AppTripsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search/': {
      id: '/_app/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof AppSearchIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/': {
      id: '/_app/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/favorites/': {
      id: '/_app/favorites/'
      path: '/favorites'
      fullPath: '/favorites/'
      preLoaderRoute: typeof AppFavoritesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budget/': {
      id: '/_app/budget/'
      path: '/budget'
      fullPath: '/budget/'
      preLoaderRoute: typeof AppBudgetIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/register/': {
      id: '/_app/auth/register/'
      path: '/auth/register'
      fullPath: '/auth/register/'
      preLoaderRoute: typeof AppAuthRegisterIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/logout/': {
      id: '/_app/auth/logout/'
      path: '/auth/logout'
      fullPath: '/auth/logout/'
      preLoaderRoute: typeof AppAuthLogoutIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auth/login/': {
      id: '/_app/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AppAuthLoginIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppBudgetIndexRoute: typeof AppBudgetIndexRoute
  AppFavoritesIndexRoute: typeof AppFavoritesIndexRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
  AppSearchIndexRoute: typeof AppSearchIndexRoute
  AppTripsIndexRoute: typeof AppTripsIndexRoute
  AppAuthLoginIndexRoute: typeof AppAuthLoginIndexRoute
  AppAuthLogoutIndexRoute: typeof AppAuthLogoutIndexRoute
  AppAuthRegisterIndexRoute: typeof AppAuthRegisterIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppBudgetIndexRoute: AppBudgetIndexRoute,
  AppFavoritesIndexRoute: AppFavoritesIndexRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
  AppSearchIndexRoute: AppSearchIndexRoute,
  AppTripsIndexRoute: AppTripsIndexRoute,
  AppAuthLoginIndexRoute: AppAuthLoginIndexRoute,
  AppAuthLogoutIndexRoute: AppAuthLogoutIndexRoute,
  AppAuthRegisterIndexRoute: AppAuthRegisterIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
